import { ARC_ANCHOR_BODIES } from "./config.js";
import { CSS } from "./css.js";
import { esc } from "./http.js";

// Fail-safe slug->section mapping for arc-page deep links (§11.1 guardrail:
// "a wrong deep link is worse than a missing one"). Runs the exact same
// stripInlineStyles -> buildSectionToc pipeline renderDigestPage itself runs
// on body_html (see there) so the #sN ids this produces line up byte-for-
// byte with what that digest's OWN page actually renders — this is never
// reimplemented or approximated, just re-run on the same input.
//
// Always the ENGLISH body_html, never body_html_hu, regardless of which
// language this arc page is being read in: derive_topics (notification-
// digest repo, digest/publish.py) derives every topic label from the
// English body_md's own `## ` headings, so an English heading is the only
// text a topic label can ever have come from — matching against the HU
// translation's (differently worded) headings would just never match.
//
// Exact match preferred (labels under 80 chars are never truncated, so the
// heading and the label are identical strings); falls back to startsWith
// (the label IS the heading truncated to 80 chars — see derive_topics) only
// when that resolves to exactly one candidate. Zero or multiple candidates
// (ambiguous — two sections whose text happens to collide) both return
// null, which renders as a fragment-less link to the digest page itself
// (see renderArcAppearance) rather than a guess that might land on the
// wrong section.
// Split in two so the expensive half runs once per BODY and the cheap half
// once per APPEARANCE: sectionsOfBody is the full stripInlineStyles ->
// buildSectionToc regex pipeline over a body that can be megabytes, and an
// arc revisiting the same digest under several labels used to re-run it for
// every appearance (up to ARC_ANCHOR_BODIES times per page view).
export function sectionsOfBody(bodyHtml) {
  return buildSectionToc(stripInlineStyles(bodyHtml)).sections;
}

export function findArcSectionAnchor(sections, label) {
  const trimmed = label.trim();
  const exact = sections.filter((s) => s.title === trimmed);
  if (exact.length === 1) return exact[0].id;
  if (exact.length > 1) return null;
  const partial = sections.filter((s) => s.title.startsWith(trimmed));
  return partial.length === 1 ? partial[0].id : null;
}

// Section index (TOC, roadmap step 5): scan the article body actually being
// shown (EN or HU — the caller passes whichever articleHtml it already
// resolved) for bare, attribute-free `<h2>title</h2>` headings. nh3 strips
// attributes upstream, so a real section heading arrives in exactly that
// shape; an h2 with any attribute or nested tag doesn't match `[^<]*` and is
// silently skipped — failing safe on an unexpected shape rather than
// guessing at it.
//
// The `.attention` callout's own h2 must never become a TOC entry: split the
// html on that div first (non-greedy — the div isn't expected to nest) and
// only scan/inject the segments outside it, passing the div's own segment
// through byte-for-byte. String.prototype.split with a capturing group
// interleaves the captured separator back into the result at the odd
// indices, so those are exactly the attention-div segments to skip.
//
// ids are "s1".."sN", sequential and positional across the whole article
// (numbering continues across any attention-div gap) — the id VALUE is
// generated by us, never derived from heading text, so no sanitization
// question arises for the id itself; the heading text stays untouched other
// than gaining the id attribute.
export function buildSectionToc(articleHtml) {
  const parts = articleHtml.split(/(<div class="attention">[\s\S]*?<\/div>)/);
  const sections = [];
  let n = 0;
  const html = parts
    .map((part, i) => {
      if (i % 2 === 1) return part; // attention-div segment: pass through
      return part.replace(/<h2>([^<]*)<\/h2>/g, (_match, title) => {
        n += 1;
        const id = `s${n}`;
        sections.push({ id, title: title.trim() });
        return `<h2 id="${id}">${title}</h2>`;
      });
    })
    .join("");
  return { html, sections };
}

// Citation-chip hover titles (roadmap step 7 — polish): a bare `<a
// class="cite" href="...">¹</a>` chip tells the reader "there's a citation
// here" but not where it goes. Add a `title` naming the destination
// hostname so hover answers that without a click. Separate pass from
// buildSectionToc (one job each), run right after it in renderDigestPage —
// not folded into that function even though both walk the same articleHtml.
//
// The regex matches the exact shape body_html's citation chips arrive in
// (nh3-sanitized upstream, hrefs are exact copies of allowlisted item
// URLs); anything that doesn't match that shape is left alone. `new URL()`
// inside try/catch fails safe: an unparseable href leaves the tag
// untouched rather than emitting a broken title. The hostname is esc()'d
// before insertion — it derives from an attribute nh3 already sanitized as
// a URL, but escaping again is free. A leading "www." is stripped for a
// slightly cleaner display string.
export function addCiteTitles(html) {
  return html.replace(/<a class="cite" href="([^"]*)">/g, (match, href) => {
    let hostname;
    try {
      hostname = new URL(href).hostname;
    } catch {
      return match; // unparseable href: leave the tag untouched, fail safe
    }
    const display = hostname.replace(/^www\./, "");
    return `<a class="cite" href="${href}" title="${esc(display)}">`;
  });
}

// Remove every style="…" attribute from the article html — see the call
// site in renderDigestPage for the full story (email-oriented inline styles
// fighting the site's theme CSS, and breaking downstream exact-shape
// regexes). Runs on nh3-normalized + emailer-generated markup only, where
// attributes are guaranteed double-quoted.
export function stripInlineStyles(html) {
  return html.replace(/ style="[^"]*"/g, "");
}
