-- Adds the optional deltas column to an EXISTING deployed digests table
-- (PLAN.md §11.3 delta persistence, ingest v4). Fresh installs don't need
-- this file -- schema.sql already includes this column for a brand-new
-- database.
--
-- Apply to the deployed D1 database with:
--   wrangler d1 execute news-digests --remote --file migrations/0007-deltas.sql
--
-- Nullable and defaults to NULL, so existing rows (all pre-v4 payloads) come
-- through unaffected, and any ingest payload with no deltas field (older app
-- version, or a window digest with no repeat-story deltas this run) keeps
-- working unchanged.
--
-- digests_fts (0005-fts-search.sql) and its sync triggers are untouched
-- here -- deltas is not an indexed text column (same reasoning as 0006's
-- topics column), so the FTS table's own schema and triggers need no
-- corresponding change.
ALTER TABLE digests ADD COLUMN deltas TEXT;
